" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

" if has("vms")
"   set nobackup		" do not keep a backup file, use versions instead
" else
"   set backup		" keep a backup file (restore to previous version)
"   if has('persistent_undo')
"     set undofile	" keep an undo file (undo changes after closing)
"   endif
" endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

" Replace tabs with spaces, and make sure one tab is 4 spaces
set expandtab 
set tabstop=4
set shiftwidth=4

" Enable automatically indenting
set autoindent
set smartindent

" Enable line numbering and make them relative to the current line
set nu
set relativenumber

" Remap escape key to easier return from insert mode
imap jj <ESC>

" Disable any bell-sounds if there should be any
set belloff=all

" Ebabke syntax highlighting
syntax on

" Search options
set hlsearch
set ignorecase
set incsearch

" Remap q to CTRL-V as this allows entering block visual mode
nnoremap q <c-v>
